ECHO checking styles
standard "source/**/*.js" --fix

ECHO building sources...
cd Tools
mono JavaScriptBundler.exe ../bundleConfig.json
cd ../
ECHO done...

ECHO building packages...
for f in nuget-packages/*.nuspec; do mono tools/nuget.exe pack $f -OutputDirectory nuget-packages/; done
ECHO done...
