@ECHO OFF
ECHO checking styles
call standard "source/**/*.js" --fix

ECHO building sources...
tools\JavaScriptBundler.exe bundleConfig.json
ECHO done...

ECHO building packages...
for /r %%x in (*.nuspec) do tools\nuget.exe pack "%%x" -OutputDirectory nuget-packages\
ECHO done...
